default_context:
  paper_id: '{{ cookiecutter.paper_id }}'
  paper_repo_name: '{{ cookiecutter.paper_repo_name }}'
  paper_short_description: '{{ cookiecutter.paper_short_description }}'
  paper_title: '{{ cookiecutter.paper_title }}'
  gitlab_group: '{{ cookiecutter.gitlab_group }}'
  main_contributor: '{{ cookiecutter.main_contributor }}'
  main_contributor_name: '{{ cookiecutter.main_contributor_name }}'
  latex_template: '{{ cookiecutter.latex_template }}'
  git_host: '{{ cookiecutter.git_host }}'
  locale: '{{ cookiecutter.locale }}'
  with_appendix: '{{ cookiecutter.with_appendix }}'
  extra_locale: '{{ cookiecutter.extra_locale }}'
  with_arxiv_package: '{{ cookiecutter.with_arxiv_package }}'
  discipline: '{{ cookiecutter.discipline }}'
  specialization: '{{ cookiecutter.specialization }}'
  supervisor: '{{ cookiecutter.supervisor }}'
  album_no: '{{ cookiecutter.album_no }}'
  beeminder: '{{ cookiecutter.beeminder_support }}'
