pipeline {

    agent {
        docker {
            image 'loxygen/autozoil'
        }
    }


    stages {

	stage ('build-pdf') {
            steps {
              withEnv(["HOME=${env.WORKSPACE}"]) {
                          sh """
pip3 install pyyaml pyminder
make clean
make
"""
            }}

            post {
                always {
                    archiveArtifacts artifacts: '{{cookiecutter.paper_id}}.pdf', fingerprint: true
                    archiveArtifacts artifacts: 'stats.txt', fingerprint: true
                }
            }

	}

	stage ('autozoil') {
            steps {
            sh """
rm -f autozoil.xml
make autozoil.xml
"""
            }

            post {
                always {
                    archiveArtifacts artifacts: 'autozoil.xml', fingerprint: true
//                    junit testResults: 'autozoil.xml'
                }
            }
	}


{% if cookiecutter.beeminder_support == 'yes' %}
        stage ('beeminder') {
            steps {
               withCredentials([string(credentialsId: 'Beeminder', variable: 'BEEMINDER_TOKEN')]) {
                          sh """
BEEMINDER_USER=ptlen make logbeeminder
"""
          }
        }
      }
{% endif %}
    }
}
